language: python
python:
  - "2.7"
# dependencies
env:
  - NETWORKX_VERSION=1.9.0
  - NETWORKX_VERSION=1.10
install:
  - pip install -q networkx==$NETWORKX_VERSION
  - pip install -r requirements.txt
  - python setup.py -q install
# command to run tests
script: nosetests --with-doctest
