language: cpp
notifications:
    email: false
compiler:
- clang
- gcc
before_install:
  - pip install --user cpp-coveralls
script:
- cd src
- ./configure --enable-gcov && make && make check
- cd ../playground
- ./Solver -solvenc -file ../benchmarks/Pigeonhole/pgn4
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
