sudo: required
language: cpp
notifications:
    email: false
compiler:
# - clang
- gcc
install:
#- cd /home/travis/
# install latest LCOV (1.9 was failing for me) [1]
- sudo apt-get install -y lcov
# install lcov to coveralls conversion + upload tool
- gem install coveralls-lcov
script:
- cd src
- make
- ./Solver -solvenc -file ../benchmarks/Pigeonhole/pgn3
- ./Solver -solvenc -file ../benchmarks/Pigeonhole/pgn5
- ./Solver -solvenc -wl -file ../benchmarks/Pigeonhole/pgn3
- ./Solver -solvenc -file -wl ../benchmarks/Pigeonhole/pgn3
- ./Solver -genben -var 2 -clause 3 -clausesize 2 -sat 1 -domain 2 -drand 1 -bool 0 -file output
- ./Solver -linenc -file simple.txt -model simple_sat.txt
- ./Solver -quadenc -file simple.txt -model simple_sat.txt
- ./Solver -b2f -file simple_sat.txt -model simple.txt
after_success:
- lcov --compat-libtool --directory . --capture --output-file coverage.info
#- coveralls-lcov coverage.info
#- cd /home/travis/
#- lcov-1.11 --directory --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test code
#- lcov-1.11  --list coverage.info # debug before upload
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
