language: cpp
notifications:
    email: false
compiler:
- clang
- gcc
before_install:
  - pip install --user cpp-coveralls
script:
- cd src
- make
- cd ../playground
- ./Solver -solvenc -file ../benchmarks/Pigeonhole/pgn4 > dev/null
after_success:
  - cpp-coveralls --exclude lib --exclude tests --gcov-options '\-lp'
