/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux nika-Latitude-3440 3.19.0-18-generic x86_64"
#define LGL_COMPILED "Fri Jun  3 17:16:39 CEST 2016"
#define LGL_RELEASED "Mon Nov  9 11:01:53 CET 2015"
#define LGL_VERSION "b85"
#define LGL_ID "3ee2a39cc143d07ea0a989cedd5008dd097a4068"
