#!/bin/sh

LC_TIME="en_US"
export LC_TIME

die () {
   echo "*** mkconfig.sh: $*" 1>&2
   exit 1
}

[ -f makefile ] || die "can not find 'makefile'"

cat<<EOF
/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
EOF

echo "#define LGL_OS \"`uname -srmn`\""
echo "#define LGL_COMPILED \"`date`\""
cat<<EOF
#define LGL_RELEASED "Mon Nov  9 11:01:53 CET 2015"
#define LGL_VERSION "b85"
#define LGL_ID "3ee2a39cc143d07ea0a989cedd5008dd097a4068"
EOF
